apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterdeploymentsets.federation.raffa.systems
spec:
  group: federation.raffa.systems
  names:
    kind: ClusterDeploymentSet
    listKind: ClusterDeploymentSetList
    plural: clusterdeploymentsets
    singular: clusterdeploymentset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            ensureNoOverlappingCIDR:
              type: boolean
            regions:
              items:
                type: string
              type: array
            registerClusters:
              type: boolean
            replicas:
              format: int64
              type: integer
            template:
              properties:
                metadata:
                  type: object
                spec:
                  properties:
                    baseDomain:
                      type: string
                    certificateBundles:
                      items:
                        properties:
                          generate:
                            type: boolean
                          name:
                            type: string
                          secretRef:
                            type: object
                        required:
                        - name
                        - secretRef
                        type: object
                      type: array
                    clusterName:
                      type: string
                    compute:
                      items:
                        properties:
                          labels:
                            additionalProperties:
                              type: string
                            type: object
                          name:
                            type: string
                          platform:
                            properties:
                              aws:
                                properties:
                                  rootVolume:
                                    properties:
                                      iops:
                                        format: int64
                                        type: integer
                                      size:
                                        format: int64
                                        type: integer
                                      type:
                                        type: string
                                    required:
                                    - iops
                                    - size
                                    - type
                                    type: object
                                  type:
                                    type: string
                                  zones:
                                    items:
                                      type: string
                                    type: array
                                required:
                                - type
                                - rootVolume
                                type: object
                              libvirt:
                                properties:
                                  image:
                                    type: string
                                  imagePool:
                                    type: string
                                  imageVolume:
                                    type: string
                                required:
                                - image
                                type: object
                              openstack:
                                properties:
                                  rootVolume:
                                    properties:
                                      iops:
                                        format: int64
                                        type: integer
                                      size:
                                        format: int64
                                        type: integer
                                      type:
                                        type: string
                                    required:
                                    - iops
                                    - size
                                    - type
                                    type: object
                                  type:
                                    type: string
                                required:
                                - type
                                - rootVolume
                                type: object
                            type: object
                          replicas:
                            format: int64
                            type: integer
                          taints:
                            items:
                              type: object
                            type: array
                        required:
                        - name
                        - replicas
                        - platform
                        type: object
                      type: array
                    controlPlane:
                      properties:
                        labels:
                          additionalProperties:
                            type: string
                          type: object
                        name:
                          type: string
                        platform:
                          properties:
                            aws:
                              properties:
                                rootVolume:
                                  properties:
                                    iops:
                                      format: int64
                                      type: integer
                                    size:
                                      format: int64
                                      type: integer
                                    type:
                                      type: string
                                  required:
                                  - iops
                                  - size
                                  - type
                                  type: object
                                type:
                                  type: string
                                zones:
                                  items:
                                    type: string
                                  type: array
                              required:
                              - type
                              - rootVolume
                              type: object
                            libvirt:
                              properties:
                                image:
                                  type: string
                                imagePool:
                                  type: string
                                imageVolume:
                                  type: string
                              required:
                              - image
                              type: object
                            openstack:
                              properties:
                                rootVolume:
                                  properties:
                                    iops:
                                      format: int64
                                      type: integer
                                    size:
                                      format: int64
                                      type: integer
                                    type:
                                      type: string
                                  required:
                                  - iops
                                  - size
                                  - type
                                  type: object
                                type:
                                  type: string
                              required:
                              - type
                              - rootVolume
                              type: object
                          type: object
                        replicas:
                          format: int64
                          type: integer
                        taints:
                          items:
                            type: object
                          type: array
                      required:
                      - name
                      - replicas
                      - platform
                      type: object
                    controlPlaneConfig:
                      properties:
                        servingCertificates:
                          properties:
                            additional:
                              items:
                                properties:
                                  domain:
                                    type: string
                                  name:
                                    type: string
                                required:
                                - name
                                - domain
                                type: object
                              type: array
                            default:
                              type: string
                          type: object
                      type: object
                    imageSet:
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    images:
                      properties:
                        hiveImage:
                          type: string
                        hiveImagePullPolicy:
                          type: string
                        installerImage:
                          type: string
                        installerImagePullPolicy:
                          type: string
                        releaseImage:
                          type: string
                      type: object
                    ingress:
                      items:
                        properties:
                          domain:
                            type: string
                          name:
                            type: string
                          namespaceSelector:
                            type: object
                          routeSelector:
                            type: object
                          servingCertificate:
                            type: string
                        required:
                        - name
                        - domain
                        type: object
                      type: array
                    manageDNS:
                      type: boolean
                    networking:
                      properties:
                        clusterNetworks:
                          items:
                            properties:
                              cidr:
                                type: string
                              hostSubnetLength:
                                format: int32
                                type: integer
                            required:
                            - cidr
                            - hostSubnetLength
                            type: object
                          type: array
                        machineCIDR:
                          type: string
                        serviceCIDR:
                          type: string
                        type:
                          type: string
                      required:
                      - machineCIDR
                      - type
                      - serviceCIDR
                      type: object
                    platform:
                      properties:
                        aws:
                          properties:
                            defaultMachinePlatform:
                              properties:
                                rootVolume:
                                  properties:
                                    iops:
                                      format: int64
                                      type: integer
                                    size:
                                      format: int64
                                      type: integer
                                    type:
                                      type: string
                                  required:
                                  - iops
                                  - size
                                  - type
                                  type: object
                                type:
                                  type: string
                                zones:
                                  items:
                                    type: string
                                  type: array
                              required:
                              - type
                              - rootVolume
                              type: object
                            region:
                              type: string
                            userTags:
                              additionalProperties:
                                type: string
                              type: object
                          required:
                          - region
                          type: object
                        libvirt:
                          properties:
                            URI:
                              type: string
                            defaultMachinePlatform:
                              properties:
                                image:
                                  type: string
                                imagePool:
                                  type: string
                                imageVolume:
                                  type: string
                              required:
                              - image
                              type: object
                            masterIPs:
                              items:
                                format: byte
                                type: string
                              type: array
                            network:
                              properties:
                                if:
                                  type: string
                                ipRange:
                                  type: string
                                name:
                                  type: string
                              required:
                              - name
                              - if
                              - ipRange
                              type: object
                          required:
                          - URI
                          - network
                          - masterIPs
                          type: object
                      type: object
                    platformSecrets:
                      properties:
                        aws:
                          properties:
                            credentials:
                              type: object
                          required:
                          - credentials
                          type: object
                      type: object
                    preserveOnDelete:
                      type: boolean
                    pullSecret:
                      type: object
                    sshKey:
                      type: object
                  required:
                  - clusterName
                  - baseDomain
                  - networking
                  - controlPlane
                  - compute
                  - platform
                  - pullSecret
                  - platformSecrets
                  type: object
              type: object
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
