apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespacefederations.federation.raffa.systems
spec:
  group: federation.raffa.systems
  names:
    kind: NamespaceFederation
    listKind: NamespaceFederationList
    plural: namespacefederations
    singular: namespacefederation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterRegistryNamespace:
              type: string
            clusters:
              items:
                properties:
                  adminSecretRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    type: object
                  name:
                    type: string
                type: object
              type: array
            domains:
              items:
                pattern: (?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]
                type: string
              pattern: (?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]
              type: array
            federatedTypes:
              items:
                type: object
              type: array
          type: object
        status:
          properties:
            clusterRegistrationStatuses:
              items:
                properties:
                  cluster:
                    type: string
                  status:
                    type: string
                type: object
              type: array
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
