apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: federation-lifecycle-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - federation-lifecycle-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - federation.raffa.systems
  resources:
  - '*'
  - multiplenamespacefederations
  - clusterdeploymentsets
  verbs:
  - '*'
- apiGroups:
  - hive.openshift.io
  resources:
  - '*'
  verbs:
  - '*'  
- apiGroups:
  - core.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'  
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'    
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - '*'
  verbs:
  - '*' 
- apiGroups:
  - multiclusterdns.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'   
- apiGroups:
  - cloudcredential.openshift.io
  resources:
  - '*'
  verbs:
  - '*'  
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'  

  